#docker build -t mam10eks/okapi-pack:0.0.1-dev -f Dockerfile.dev .
FROM ubuntu:18.04

WORKDIR /okapi-pack

RUN apt-get update \
	&& apt-get install -y build-essential wget \
	&& cd /okapi-pack \
	&& wget https://www.staff.city.ac.uk/~andym/OKAPI-PACK/package/okapi-2.53.tar.gz \
	&& tar -xf okapi-2.53.tar.gz

ENV PATH=/okapi-pack/okapi-pack/bin:${PATH}
ENV LD_LIBRARY_PATH=/usr/lib/i386-linux-gnu/

RUN dpkg --add-architecture i386 \
	&& apt-get update \
	&& apt-get install -y libc6:i386 libncurses5:i386 libstdc++6:i386 libexpat1:i386 libexpat1-dev:i386 git wget curl htop \
	&& ln -s /usr/lib/i386-linux-gnu/libexpat.so /usr/lib/i386-linux-gnu/libexpat.so.0

